# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0eef7a673b62abe063e3de185e6ef13fedc4f39e392386ad6d6fa9c301dafe3a4c59b02641f060d8cd681de2e9f10c3e78b193bb25c72a4db6c38f410367f9d2

test:
  secret_key_base: 2884a136c790cee0d8ebd3d1f88fb9ef67a628f8034cbf220d9c234eff29c099eb0be25b22b7653306ecd1535f2a78526ddadf4ee534bc6b4768f09d588608b1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
